#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use ScCli\App;

$app = new App();

$app->registerCommand('setupDatabases', function (array $argv) use ($app) {
    $app->setupDatabases();
});

$app->registerCommand('copy', function (array $argv) use ($app) {
    $app->copy($argv);
});

$app->registerCommand('help', function (array $argv) use ($app) {
    $app->help();
});

$app->runCommand($argv);